name: Health Check

on:
  push:
    branches:
      - main

jobs:
  health_check:
    runs-on: ubuntu-22.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-zaim.onrender.com/
          follow-redirect: false
          max-attempts: 3
          retry-delay: 5s
          retry-all: false
